"""
TrustGuard REALKEY Security Module.

Provides cryptographic authorization, WebAuthn/Passkey registration and
verification, canonical payment bundling, and proof of non-repudiation.
"""

from security.realkey.challenge import (
    ApprovalChallenge,
    AuthenticationChallenge,
    ChallengeAlreadyUsedError,
    ChallengeError,
    ChallengeExpiredError,
    ChallengeMismatchError,
    ChallengeNotFoundError,
    PaymentHashMismatchError,
    RegistrationChallenge,
    challenge_store,
)
from security.realkey.webauthn_verifier import (
    ApprovalExpiredError,
    InactiveApproverError,
    InvalidCredentialFormatError,
    InvalidOriginError,
    InvalidRPIDError,
    InvalidSignatureError,
    SignCountReplayError,
    UnknownCredentialError,
    VerifiedAuthenticationResult,
    VerifiedPaymentApprovalResult,
    VerifiedRegistrationResult,
    WebAuthnAuthenticationError,
    WebAuthnRegistrationError,
    WebAuthnSecurityError,
    generate_authentication_options,
    generate_registration_options,
    pem_to_cose,
    verify_authentication,
    verify_payment_approval,
    verify_registration,
)
from security.realkey.bundle import (
    PaymentBundleError,
    PaymentBundleExpiredError,
    PaymentBundleValidationError,
    REQUIRED_PAYMENT_BUNDLE_FIELDS,
    calculate_bundle_expiry,
    canonicalize_payment_bundle,
    create_payment_bundle,
    create_payment_bundle_from_model,
    format_utc_timestamp,
    generate_payment_nonce,
    hash_payment_bundle,
    is_bundle_expired,
    parse_utc_timestamp,
    validate_payment_bundle,
    verify_bundle_not_expired,
)
from security.realkey.simulator import VirtualWebAuthnClient
from security.realkey.tamper_demo import (
    TamperVerificationResult,
    demonstrate_tamper_detection,
    simulate_payment_tampering,
    verify_bundle_integrity,
)
from security.realkey.replay_guard import (
    ApproverAlreadySignedError,
    NonceAlreadyUsedError,
    PaymentAlreadyAuthorizedError,
    ReplayGuardError,
    SignatureReplayError,
    log_replay_event,
    verify_all_replay_guards,
    verify_approver_not_already_signed,
    verify_nonce_unused,
    verify_payment_not_authorized,
    verify_signature_payload_not_replayed,
)
from security.realkey.sod import (
    SeparationOfDutiesError,
    get_authoritative_preparer,
    log_sod_violation,
    verify_separation_of_duties,
)

__all__ = [
    # Challenge
    "challenge_store",
    "RegistrationChallenge",
    "AuthenticationChallenge",
    "ApprovalChallenge",
    "ChallengeError",
    "ChallengeNotFoundError",
    "ChallengeExpiredError",
    "ChallengeAlreadyUsedError",
    "ChallengeMismatchError",
    "PaymentHashMismatchError",
    # WebAuthn registration & authentication
    "generate_registration_options",
    "verify_registration",
    "generate_authentication_options",
    "verify_authentication",
    "verify_payment_approval",
    "pem_to_cose",
    "VerifiedRegistrationResult",
    "VerifiedAuthenticationResult",
    "VerifiedPaymentApprovalResult",
    "WebAuthnSecurityError",
    "WebAuthnRegistrationError",
    "WebAuthnAuthenticationError",
    "ApprovalExpiredError",
    "InvalidOriginError",
    "InvalidRPIDError",
    "InvalidCredentialFormatError",
    "InvalidSignatureError",
    "SignCountReplayError",
    "UnknownCredentialError",
    "InactiveApproverError",
    "VirtualWebAuthnClient",
    # Payment Bundle & Canonical Hashing
    "REQUIRED_PAYMENT_BUNDLE_FIELDS",
    "PaymentBundleError",
    "PaymentBundleValidationError",
    "PaymentBundleExpiredError",
    "generate_payment_nonce",
    "calculate_bundle_expiry",
    "parse_utc_timestamp",
    "format_utc_timestamp",
    "validate_payment_bundle",
    "create_payment_bundle",
    "create_payment_bundle_from_model",
    "canonicalize_payment_bundle",
    "hash_payment_bundle",
    "is_bundle_expired",
    "verify_bundle_not_expired",
    # Tamper Detection Demo
    "TamperVerificationResult",
    "simulate_payment_tampering",
    "demonstrate_tamper_detection",
    "verify_bundle_integrity",
    # Replay Protection
    "ReplayGuardError",
    "NonceAlreadyUsedError",
    "ApproverAlreadySignedError",
    "PaymentAlreadyAuthorizedError",
    "SignatureReplayError",
    "verify_nonce_unused",
    "verify_approver_not_already_signed",
    "verify_payment_not_authorized",
    "verify_signature_payload_not_replayed",
    "log_replay_event",
    "verify_all_replay_guards",
    # Separation of Duties
    "SeparationOfDutiesError",
    "get_authoritative_preparer",
    "verify_separation_of_duties",
    "log_sod_violation",
]

